# Generated by Django 4.2.8 on 2024-02-22 15:17

import climategame.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("climategame", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hitassignment",
            name="scenario_order",
            field=models.JSONField(default=climategame.models.default_json),
        ),
        migrations.AddField(
            model_name="humaninttask",
            name="assignment_review_policy",
            field=models.JSONField(default=climategame.models.default_json),
        ),
        migrations.AddField(
            model_name="humaninttask",
            name="hit_layout_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="humaninttask",
            name="hit_layout_parameters",
            field=models.JSONField(default=climategame.models.default_json),
        ),
        migrations.AddField(
            model_name="humaninttask",
            name="hit_review_policy",
            field=models.JSONField(default=climategame.models.default_json),
        ),
        migrations.AddField(
            model_name="humaninttask",
            name="hit_type_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="humaninttask",
            name="requester_annotation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="humaninttask",
            name="unique_request_token",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="attentioncheck",
            name="valid_response",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="demographicsanswer",
            name="answer",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="demographicsquestion",
            name="options",
            field=models.JSONField(default=climategame.models.default_json),
        ),
        migrations.AlterField(
            model_name="environmentalscenario",
            name="name",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="environmentalscenario",
            name="scenario",
            field=models.JSONField(default=climategame.models.default_json),
        ),
        migrations.AlterField(
            model_name="game",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="keywords",
            field=models.JSONField(default=climategame.models.default_json),
        ),
        migrations.AlterField(
            model_name="game",
            name="question",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="hitassignment",
            name="answer",
            field=models.JSONField(default=climategame.models.default_json),
        ),
        migrations.AlterField(
            model_name="hitassignment",
            name="assignment_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="hitassignment",
            name="status",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hitassignment",
            name="worker_id",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="humaninttask",
            name="assignment_duration_seconds",
            field=models.IntegerField(default=3600),
        ),
        migrations.AlterField(
            model_name="humaninttask",
            name="auto_approval_delay_seconds",
            field=models.IntegerField(default=3600),
        ),
        migrations.AlterField(
            model_name="humaninttask",
            name="hit_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="humaninttask",
            name="lifetime_seconds",
            field=models.IntegerField(default=3600),
        ),
        migrations.AlterField(
            model_name="humaninttask",
            name="max_assignments",
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name="humaninttask",
            name="qualification_requirements",
            field=models.JSONField(default=climategame.models.default_json),
        ),
        migrations.AlterField(
            model_name="humaninttask",
            name="reward",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="humaninttask",
            name="status",
            field=models.CharField(default="Assignable", max_length=50),
        ),
        migrations.AlterField(
            model_name="humaninttask",
            name="turk_submit_to",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="roundselection",
            name="crop",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="roundselection",
            name="eor_crop_income",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="roundselection",
            name="eor_profit",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="roundselection",
            name="round",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="roundselection",
            name="technology",
            field=models.BooleanField(default=False),
        ),
    ]
