# Generated by Django 4.2.8 on 2024-02-22 18:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("climategame", "0002_hitassignment_scenario_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hitassignment",
            name="turk_submit_to",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="DemogrphicsQuestionChoices",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("choice", models.CharField(max_length=100)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="climategame.demographicsquestion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
